export * from "~/presets/authjs"
export * from "~/presets/base"
export * from "~/presets/bot"
export * from "~/presets/dash"
export * from "~/presets/database"
export * from "~/presets/discord"
export * from "~/presets/docs"
export * from "~/presets/trpc"
export * from "~/presets/twitch"
export * from "~/presets/www"

export * from "~/merge"
